name: reader_mvp
description: MVP reader app (camera + OCR + TTS)
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # カメラ機能
  camera: ^0.10.5+9

  # 端末内OCR (ML Kit Text Recognition)
  google_mlkit_text_recognition: ^0.10.0

  # 読み上げ
  flutter_tts: ^3.8.3

  # 権限ダイアログ
  permission_handler: ^11.3.1

  # 一時保存など
  path_provider: ^2.1.4

  # 画像処理（必要な場合）
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # もし assets を使う場合は以下を有効化
  # assets:
  #   - assets/
