name: Android APK (force V2 debug)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # 1) 既存の android を捨てて毎回V2で作り直す
      - name: Clean and recreate Android (V2)
        run: |
          rm -rf android
          flutter create . --platforms=android --org com.example --project-name reader_mvp --overwrite

      # 2) MainActivity を明示的にV2に上書き（Kotlin）
      - name: Ensure MainActivity is V2
        run: |
          mkdir -p android/app/src/main/kotlin/com/example/reader_mvp
          cat > android/app/src/main/kotlin/com/example/reader_mvp/MainActivity.kt <<'KOT'
          package com.example.reader_mvp
          import io.flutter.embedding.android.FlutterActivity
          class MainActivity: FlutterActivity()
          KOT

      # 3) 念のためV1の痕跡がないかチェック（あれば失敗させる）
      - name: Check for V1 embedding (guard)
        run: |
          if grep -R "io.flutter.app.FlutterActivity" -n android || grep -R "GeneratedPluginRegistrant" -n android; then
            echo "Found old V1 embedding code"; exit 1;
          fi

      # 4) Tesseract データ同梱
      - name: Prepare tessdata
        run: |
          mkdir -p assets/tessdata
          curl -L -o assets/tessdata/jpn.traineddata https://github.com/tesseract-ocr/tessdata_fast/raw/main/jpn.traineddata
          curl -L -o assets/tessdata/jpn_vert.traineddata https://github.com/tesseract-ocr/tessdata_fast/raw/main/jpn_vert.traineddata

      - name: flutter pub get
        run: flutter pub get -v | tee pubget.log

      # 5) Debug でビルド（デバッグ署名つき→端末にそのまま入る）
      - name: Build APK (debug)
        run: flutter build apk --debug -v | tee build.log

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            build.log
            pubget.log
            **/*.log
            **/*.stacktrace
            android/**/outputs/logs/*
