name: Android APK

on:
  # 手動だけで実行（自動では走らない）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Flutter doctor
        run: flutter doctor -v

      # ZIPの場所を自動検出（repo直下 or reader_mvp/ 配下など）
      - name: Locate ZIP
        id: locate
        run: |
          set -e
          for p in "reader_mvp_ci.zip" "reader_mvp/reader_mvp_ci.zip"; do
            if [ -f "$p" ]; then
              echo "zip=$p" >> $GITHUB_OUTPUT
              echo "Found: $p"
              exit 0
            fi
          done
          echo "ZIP not found"; ls -la
          exit 1

      - name: Unzip project
        run: |
          unzip -o "${{ steps.locate.outputs.zip }}" -d .
          # 必要ならFlutterのandroid骨格を生成（既にあれば何もしない）
          if [ ! -d android ]; then flutter create . --platforms=android; fi
          ls -la
          ls -R android/app/src || true
          ls -R lib || true

      # tessdata（日本語・縦書き）を同梱
      - name: Prepare tessdata
        run: |
          mkdir -p assets/tessdata
          curl -L -o assets/tessdata/jpn.traineddata https://github.com/tesseract-ocr/tessdata_fast/raw/main/jpn.traineddata
          curl -L -o assets/tessdata/jpn_vert.traineddata https://github.com/tesseract-ocr/tessdata_fast/raw/main/jpn_vert.traineddata
          ls -la assets/tessdata

      - name: Flutter pub get (logged)
        run: flutter pub get -v | tee pubget.log

      - name: Build APK (release, verbose)
        env:
          GRADLE_OPTS: "-Dorg.gradle.logging.stacktrace=all -Dorg.gradle.console=plain"
        run: |
          set -e
          flutter build apk --release -v | tee build.log
          echo "---- outputs ----" | tee -a build.log
          ls -R build/app/outputs | tee -a build.log

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reader_mvp-release-apk
          path: build/app/outputs/**/*

      - name: Upload logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            build.log
            pubget.log
            **/*.log
            **/*.stacktrace
            android/**/outputs/logs/*
