name: Android APK (clean build)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # ★毎回Androidフォルダを作り直してV2埋め込みにする
      - name: Clean and recreate Android folder
        run: |
          rm -rf android
          flutter create . --platforms=android --org com.example --project-name reader_mvp --overwrite

      - name: Prepare tessdata
        run: |
          mkdir -p assets/tessdata
          curl -L -o assets/tessdata/jpn.traineddata https://github.com/tesseract-ocr/tessdata_fast/raw/main/jpn.traineddata
          curl -L -o assets/tessdata/jpn_vert.traineddata https://github.com/tesseract-ocr/tessdata_fast/raw/main/jpn_vert.traineddata

      - name: flutter pub get
        run: flutter pub get

      - name: Build APK (debug)
 　　　　run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
