name: Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Show Flutter version
        run: flutter --version

      # ← ここを強化：ZIPの実在場所を自動で見つける
      - name: Locate ZIP
        id: locate
        run: |
          set -e
          if [ -f reader_mvp_ci.zip ]; then
            echo "zip=reader_mvp_ci.zip" >> $GITHUB_OUTPUT
            echo "Found ZIP at repo root"
          elif [ -f reader_mvp/reader_mvp_ci.zip ]; then
            echo "zip=reader_mvp/reader_mvp_ci.zip" >> $GITHUB_OUTPUT
            echo "Found ZIP under reader_mvp/"
          else
            echo "ZIP not found. Listing files:"
            ls -la
            exit 1
          fi

      - name: Unzip project
        run: |
          unzip -o "${{ steps.locate.outputs.zip }}" -d .
          # Android雛形が無ければ生成（あっても上書きOK）
          flutter create . --platforms=android --overwrite
          # 置いてあればマニフェストを適用（無ければ無視）
        

      - name: Prepare tessdata (jpn, jpn_vert)
        run: |
          mkdir -p assets/tessdata
          curl -L -o assets/tessdata/jpn.traineddata https://github.com/tesseract-ocr/tessdata_fast/raw/main/jpn.traineddata
          curl -L -o assets/tessdata/jpn_vert.traineddata https://github.com/tesseract-ocr/tessdata_fast/raw/main/jpn_vert.traineddata

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: reader_mvp-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
